# Generated by Django 4.2.2 on 2023-06-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('website', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
