# Generated by Django 4.2 on 2023-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
