# Generated by Django 4.2 on 2023-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0005_alter_contacts_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.URLField(),
        ),
    ]
